FROM node:24-alpine

COPY . /opt

WORKDIR /opt

RUN npm install && npm run build       

Run apk update && apk add apache2 -y

EXPOSE 80

CMD ["apachectl", "-D", "FOREGROUND"]
# ENTRYPOINT ["apachectl", "-D", "FOREGROUND"]



