FROM maven:3.8.3-openjdk-17

COPY . /opt/

WORKDIR /opt

RUN rm -f src\main\resources\application.properties && \
    cp -f application.properties src\main\resources\application.properties && \
    mvn clean package -Dskiptests

WORKDIR /target

Expose 8080

ENTRYPOINT ["java","-jar"]
CMD ["student-registration-backend"]
