version: '3.8'

services:
  # MariaDB Database
  database:
    image: mariadb:10.11
    container_name: easycrud-db-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: student_db
      MYSQL_USER: easycrud_user
      MYSQL_PASSWORD: easycrud_password
    ports:
      - "3306:3306"
    volumes:
      - db_data_dev:/var/lib/mysql
      - ./backend/database_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - easycrud-network-dev

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: easycrud-backend-dev
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/student_db
      SPRING_DATASOURCE_USERNAME: easycrud_user
      SPRING_DATASOURCE_PASSWORD: easycrud_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: true
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - easycrud-network-dev

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BACKEND_HOST: 34.201.59.80
        BACKEND_PORT: 8080
    container_name: easycrud-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - easycrud-network-dev

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: easycrud-nginx-dev
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - easycrud-network-dev

volumes:
  db_data_dev:
    driver: local

networks:
  easycrud-network-dev:
    driver: bridge 